# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ["main.py"],
    pathex=[],
    binaries=[],
    datas=[
        ("assets/fonts", "assets/fonts"),
        ("assets/sounds", "assets/sounds"),
        ("logo.png", "."),
        ("logo.ico", "."),
    ],
    hiddenimports=[
        "alarm_sounds",
        "autostart",
        "cleaner",
        "hotkeys",
        "media_player_ui",
        "productivity",
        "recorder_ui",
        "screen_recorder",
        "screenshot_app",
        "simple_boards",
        "skin",
        "settings_ui",
        "storage",
        "theme",
        "world_clock_ui",
        "cv2",
        "imageio_ffmpeg",
        "mss",
        "numpy",
        "pythoncom",
        "pywintypes",
        "sounddevice",
        "vlc",
        "win32api",
        "win32con",
        "win32gui",
        "win32ui",
        "yt_dlp",
        "pytz",
        "PyQt6.QtMultimedia",
        "PyQt6.QtMultimediaWidgets",
        "PyQt6.QtNetwork",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "PyQt6.QtDesigner",
        "PyQt6.QtPdf",
        "PyQt6.QtQml",
        "PyQt6.QtQuick",
        "IPython",
        "jupyter",
        "matplotlib",
        "scipy",
        "tensorflow",
        "tkinter",
        "torch",
        "websockets",
        "win32com",
    ],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="Clock-Alarm",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    icon="logo.ico",
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="Clock-Alarm",
)
